### ISSUE TITLE
Is this working with podfile "use_frameworks!" ?

### ISSUE THREAD

**Issue by speed1speed1** [unimodules/react-native-unimodules#29] opened 2019-04-13 08:34 UTC
I can't build this with "react-native-charts-wrapper".
Because I need use "use_frameworks!" in the podfile.
Any solutions for this?

RN 0.59.1

**Comment by ferrannp** [comment] 2019-04-24 15:16
I am having the same problem with the exact same library that requires `use_frameworks!`.

![image](https://user-images.githubusercontent.com/774577/56671239-92875580-66b4-11e9-8d70-49b1020517ae.png)

Podfile:

```
platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

use_frameworks!

target 'MyApp' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  use_unimodules!

  swift5 = ['Charts', 'SwiftyJSON']

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if swift5.include?(target.name)
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
    end
  end
end
```

**Comment by brentvatne** [comment] 2019-04-24 21:41
cc @sjchmiela

**Comment by wuxudong** [comment] 2019-04-25 00:30
A temporary workaround for react-native-chart-wrapper, [link](https://github.com/wuxudong/react-native-charts-wrapper/issues/525)

**Comment by tsapeta** [comment] 2019-04-25 09:10
I can confirm that unimodules don't work with `use_frameworks!`. The cause is that we declare some log functions in the core module and the plan was to implement them inside platform adapters (it's implemented in `@unimodules/react-native-adapter`), however it turned out this way doesn't work well when using frameworks. The solution would be to move the implementation from the adapter to the core module. Hopefully, we'll get this fixed soon 🙂

**Comment by sjchmiela** [comment] 2019-04-26 09:31
Looks like I was able to add support for `use_frameworks!` with unimodules in https://github.com/expo/expo/pull/4080. We'll release a package update once the fix is merged. Thanks for notifying of this problem!

**Closed** 2019-04-29 14:21 UTC
